package org.hyouman.entities;
// Generated Apr 24, 2017 1:11:45 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CreditCard generated by hbm2java
 */
public class CreditCard implements java.io.Serializable {

	private Integer id;
	private User user;
	private String cardNumber;
	private String nameOnCard;
	private String expiryMonth;
	private String expiryYear;
	private String cvv;
	private Set<Donation> donations = new HashSet<Donation>(0);

	public CreditCard() {
	}

	public CreditCard(User user) {
		this.user = user;
	}

	public CreditCard(User user, String cardNumber, String nameOnCard, String expiryMonth, String expiryYear,
			String cvv, Set<Donation> donations) {
		this.user = user;
		this.cardNumber = cardNumber;
		this.nameOnCard = nameOnCard;
		this.expiryMonth = expiryMonth;
		this.expiryYear = expiryYear;
		this.cvv = cvv;
		this.donations = donations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	public String getExpiryMonth() {
		return this.expiryMonth;
	}

	public void setExpiryMonth(String expiryMonth) {
		this.expiryMonth = expiryMonth;
	}

	public String getExpiryYear() {
		return this.expiryYear;
	}

	public void setExpiryYear(String expiryYear) {
		this.expiryYear = expiryYear;
	}

	public String getCvv() {
		return this.cvv;
	}

	public void setCvv(String cvv) {
		this.cvv = cvv;
	}

	public Set<Donation> getDonations() {
		return this.donations;
	}

	public void setDonations(Set<Donation> donations) {
		this.donations = donations;
	}

}
