package org.hyouman.entities;
// Generated Apr 24, 2017 1:11:45 AM by Hibernate Tools 5.2.1.Final

/**
 * Donation generated by hbm2java
 */
public class Donation implements java.io.Serializable {

	private Integer id;
	private CreditCard creditCard;
	private Story story;
	private User user;
	private Double amount;
	private String status;
	private String initiatedDate;
	private String completedDate;

	public Donation() {
	}

	public Donation(User user) {
		this.user = user;
	}

	public Donation(CreditCard creditCard, Story story, User user, Double amount, String status, String initiatedDate,
			String completedDate) {
		this.creditCard = creditCard;
		this.story = story;
		this.user = user;
		this.amount = amount;
		this.status = status;
		this.initiatedDate = initiatedDate;
		this.completedDate = completedDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CreditCard getCreditCard() {
		return this.creditCard;
	}

	public void setCreditCard(CreditCard creditCard) {
		this.creditCard = creditCard;
	}

	public Story getStory() {
		return this.story;
	}

	public void setStory(Story story) {
		this.story = story;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getInitiatedDate() {
		return this.initiatedDate;
	}

	public void setInitiatedDate(String initiatedDate) {
		this.initiatedDate = initiatedDate;
	}

	public String getCompletedDate() {
		return this.completedDate;
	}

	public void setCompletedDate(String completedDate) {
		this.completedDate = completedDate;
	}

}
