package org.hyouman.entities;
// Generated Apr 24, 2017 1:11:45 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable {

	private Integer id;
	private String title;
	private String subTitle;
	private String description;
	private byte[] picture;
	private String status;
	private Set<Story> stories = new HashSet<Story>(0);

	public Program() {
	}

	public Program(String title, String subTitle, String description, byte[] picture, String status,
			Set<Story> stories) {
		this.title = title;
		this.subTitle = subTitle;
		this.description = description;
		this.picture = picture;
		this.status = status;
		this.stories = stories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Story> getStories() {
		return this.stories;
	}

	public void setStories(Set<Story> stories) {
		this.stories = stories;
	}

}
