package org.hyouman.entities;
// Generated Apr 24, 2017 1:11:45 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Story generated by hbm2java
 */
public class Story implements java.io.Serializable {

	private Integer id;
	private Program program;
	private User user;
	private String title;
	private String subTitle;
	private String description;
	private Double targetAmount;
	private Double expensePerDay;
	private String status;
	private String startDate;
	private String endDate;
	private byte[] picture;
	private Set<Donation> donations = new HashSet<Donation>(0);

	public Story() {
	}

	public Story(Program program, User user, String title, String subTitle, String description, Double targetAmount,
			Double expensePerDay, String status, String startDate, String endDate, byte[] picture,
			Set<Donation> donations) {
		this.program = program;
		this.user = user;
		this.title = title;
		this.subTitle = subTitle;
		this.description = description;
		this.targetAmount = targetAmount;
		this.expensePerDay = expensePerDay;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
		this.picture = picture;
		this.donations = donations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getTargetAmount() {
		return this.targetAmount;
	}

	public void setTargetAmount(Double targetAmount) {
		this.targetAmount = targetAmount;
	}

	public Double getExpensePerDay() {
		return this.expensePerDay;
	}

	public void setExpensePerDay(Double expensePerDay) {
		this.expensePerDay = expensePerDay;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public Set<Donation> getDonations() {
		return this.donations;
	}

	public void setDonations(Set<Donation> donations) {
		this.donations = donations;
	}

}
