package org.hyouman.entities;
// Generated Apr 24, 2017 1:11:45 AM by Hibernate Tools 5.2.1.Final

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount implements java.io.Serializable {

	private String email;
	private String password;
	private String status;

	public UserAccount() {
	}

	public UserAccount(String email) {
		this.email = email;
	}

	public UserAccount(String email, String password, String status) {
		this.email = email;
		this.password = password;
		this.status = status;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
